### ISSUE TITLE
GoLang port of your library

### ISSUE THREAD

**Issue by chrusty** [arg20/circle-to-radius#46]
Today I found myself looking for a GoLang library that can do what your JS one does - converting circles into polygons. I couldn't find anything, so I wrote this: https://github.com/chrusty/go-circle-to-polygon. I've completely copied your math, and am very grateful for your work!

This is not an "issue" as such - just wanted to let you know, and to say thanks.

**Comment by johachi** [comment]
Thank you for the message! It makes us very happy to hear. I saw that you have also referenced this repository. Thank you very much!
 
Totally a coincidence, but I'm actually learning GoLang right now. I will let this "issue" stay open for a little longer in case @gabzim wants to comment as well. 😃

**Comment by gabzim** [comment]
Excellent! I'm glad this module was useful and @johachi has been doing most of the work maintaining lately so it's great to see how the community takes something that was very small to solve a very specific problema and grows it into multiple solutions in different languages. @johachi maybe we can reference the go implementation in our README so that anybody using go can also see it, what do you think? That way we can promote his port as well.

**Comment by johachi** [comment]
> @johachi maybe we can reference the go implementation in our README so that anybody using go can also see it, what do you think?

@gabzim, absolutely! I will make the PR and have that PR close this issue. 😃 

I will get it done this weekend.
